services:
  - type: web
    name: mortality-analysis-dashboard
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:application
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.1
    runtime: python